ALTER TABLE blog_post DROP COLUMN view_count;

CREATE TABLE post_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_post_like_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX idx_post_like_user_id ON post_like(user_id);
