CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    nickname VARCHAR(20),
    profile_image_url VARCHAR(2048),
    github_url VARCHAR(255),
    contact_email VARCHAR(254),
    oauth_provider VARCHAR(20),
    oauth_subject VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    role VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_users_lowercase_email CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN ('PENDING', 'USER', 'ADMIN')),
    CONSTRAINT ck_users_oauth_identity CHECK (
        (oauth_provider IS NULL AND oauth_subject IS NULL)
        OR (oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uk_users_nickname ON users (lower(nickname));
CREATE UNIQUE INDEX uk_users_oauth_identity ON users (oauth_provider, oauth_subject);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    session_id UUID NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_refresh_token_user_id ON refresh_token(user_id);
CREATE INDEX idx_refresh_token_expires_at ON refresh_token(expires_at);
CREATE INDEX idx_refresh_token_session_id ON refresh_token(session_id);

CREATE TABLE token_blacklist (
    session_id UUID PRIMARY KEY,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_token_blacklist_expires_at ON token_blacklist(expires_at);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_category_author_name UNIQUE (author_id, name)
);

CREATE TABLE blog_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES category(id),
    representative_image_url VARCHAR(2048),
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_blog_post_author_id ON blog_post(author_id);
CREATE INDEX idx_blog_post_created_at ON blog_post(created_at DESC);
CREATE INDEX idx_blog_post_category_id ON blog_post(category_id);
CREATE INDEX idx_blog_post_title_trgm ON blog_post USING GIN (lower(title) gin_trgm_ops);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_tag_name_trgm ON tag USING GIN (lower(name) gin_trgm_ops);

CREATE TABLE blog_post_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tag(id),
    CONSTRAINT uk_blog_post_tag UNIQUE (post_id, tag_id)
);
CREATE INDEX idx_blog_post_tag_tag_id ON blog_post_tag(tag_id);

CREATE TABLE post_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_post_like_post_user UNIQUE (post_id, user_id)
);
CREATE INDEX idx_post_like_user_id ON post_like(user_id);

CREATE TABLE comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    author_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    parent_id BIGINT REFERENCES comment(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    deleted_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_comment_not_self_parent CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE INDEX idx_comment_target_created_id ON comment(target_type, target_id, created_at, id);
CREATE INDEX idx_comment_parent_id ON comment(parent_id);
