CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_category_author_name UNIQUE (author_id, name)
);

INSERT INTO category (author_id, name, created_at, updated_at)
SELECT author_id, COALESCE(NULLIF(BTRIM(category), ''), '미분류'), MIN(created_at), MAX(updated_at)
FROM blog_post
GROUP BY author_id, COALESCE(NULLIF(BTRIM(category), ''), '미분류');

ALTER TABLE blog_post ADD COLUMN category_id BIGINT REFERENCES category(id);
UPDATE blog_post p
SET category_id = c.id
FROM category c
WHERE c.author_id = p.author_id
  AND c.name = COALESCE(NULLIF(BTRIM(p.category), ''), '미분류');
ALTER TABLE blog_post ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE blog_post DROP COLUMN category;
CREATE INDEX idx_blog_post_category_id ON blog_post(category_id);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE blog_post_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tag(id),
    CONSTRAINT uk_blog_post_tag UNIQUE (post_id, tag_id)
);
CREATE INDEX idx_blog_post_tag_tag_id ON blog_post_tag(tag_id);
